language: go
go:
- 1.6.x
- 1.7.x
- 1.9.x
- master

go-import-path: "github.com/onestay/go-new-twitch"

env:
  global:
    secure: OCrQUEsLJh9/XU6SY25xBEDL2jMvPU1gnNCjV0NI+4FNc24oRGA1kAmL49tkvK2o6zA+8lQUZ/EZvX1+Evw49Hxv982N72bzgPwi7aWOOVxzQnJok3SiJXJP0fAwr9xeXpNc9I+GqsGAZArRKLkTaUefKMSezAuyHOkhONud3c4Pe8FYc5o8IDVL6PQQO0a0GhhQzkW56askrVwHYugiY4HDoi/h3W0v4VgpYUE3mGa0of4Zv2oFcoxoW9WLBdiq7rvohOHCzccy3Tagp4pY5M1BAecL/7zb2R66AQ4kuD0r0SeqY6CGJQRSbxGT+q7n2IEc/32IL/M8pJjt7v2DXQ6buJhfZd2kDOloDQuiVTGWjo0Bdod0u0KzMwmB0jyfA17lVXdOnrIcCjR8bPPPU5G4kTGECr5CPBfyU7iBPhkGTuPFJbVwZ4ka1MXKSGxVbKbH7LxDB4b4g0q9++l+w/6EjWv1AHfNpmcyAiTpDNNU30UQxwyQNZpz/MLP2v5UNDO2co7D+k2k78j1D32iq0q/RHSfn9t4lSR9yKL88dQVVCmIvyjH9onLmYAd/3WowhTjeOfuB30i4472/59e70MReBLqCu78s1LbfxpSj+r+OsxChEiLgydVxG/wcDWUbLeZU7UkVppCbN2D9+ret0LI4VPZ7LhKXGHTWO3sC70=
